apiVersion: apps/v1
kind: Deployment
metadata:
  name: corrector-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corrector-api
  template:
    metadata:
      labels:
        app: corrector-api
    spec:
      containers:
        - name: corrector-api
          image: ghcr.io/lngeth/fr_corrector/corrector_api:7eb71c7756e193864f654a66029b86243dd902a8
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ghcr-secret